### ISSUE TITLE
AutoRound/Examples dependency is injected to AutoRound pkg dependency

### ISSUE THREAD

**Issue by Qubitium** [intel/auto-round#177]
GPTQModel has merged AutorRound integration via PR https://github.com/ModelCloud/GPTQModel/pull/166 but we find the the CI tests is importing auto-gptq (via auto-round depends)  as dependency which is strange to us since the only auto-gptq code in AutoRound is in examples. 

Can examples/require*txt not be merge into auto-round pkg depends proper?

**Comment by wenhuach21** [comment]
> GPTQModel has merged AutorRound integration via PR [ModelCloud/GPTQModel#166](https://github.com/ModelCloud/GPTQModel/pull/166) but we find the the CI tests is importing auto-gptq (via auto-round depends) as dependency which is strange to us since the only auto-gptq code in AutoRound is in examples.
> 
> Can examples/require*txt not be merge into auto-round pkg depends proper?

Thank you for integrating Autoround. We should have not merge the example/requirement.txt  in the main branch.  

During the  model packing, we need to import some packing functions from autogptq.

BTW, our API has changed a little to support the new features

**Comment by Qubitium** [comment]
@wenhuach21 We are closely following pending v0.3 autoround release in https://github.com/ModelCloud/GPTQModel/issues/179 as there are lots of feature and internal api change. Is there an estimated release date for autoround v0.3?

**Comment by wenhuach21** [comment]
> @wenhuach21 We are closely following pending v0.3 autoround release in [ModelCloud/GPTQModel#179](https://github.com/ModelCloud/GPTQModel/issues/179) as there are lots of feature and internal api change. Is there an estimated release date for autoround v0.3?

about 2 weeks

**Comment by wenhuach21** [comment]
sorry for the late. V0.3 has been released
