### ISSUE TITLE
Serialization in multiple formats

### ISSUE THREAD

**Issue by benjamin-marie** [intel/auto-round#234]
When I serialize the model, I would like to serialize with all the formats available, e.g., GPTQ, AWQ, and AutoRound. However, it doesn't seem possible. If I first save with GPTQ format and then try AutoRound format, it doesn't work. Is the model discarded from memory once the model is serialized?
It seems that I have to rerun the quantization and then serialize it to another format.

**Comment by wenhuach21** [comment]
if you are using the interface，set the inplace to false in save_quantized.
if you are using the example， we will support it tomorrow

**Comment by benjamin-marie** [comment]
in_place is what I was looking for. I'm not sure how I didn't see it!
Thanks a lot.
