### ISSUE TITLE
from auto_round import AutoRoundConfig

### ISSUE THREAD

**Issue by CrispStrobe** [intel/auto-round#235]
... did not work for me right now, whereas previously it did. Cannot check this further at the moment, but maybe you might want to. Environment was kaggle and colab, occured after `!pip install auto-round`, seemingly resolved per:
```
!pip uninstall auto_round -y
!pip cache remove auto_round
!pip install --no-cache-dir auto_round
from auto_round.auto_quantizer import AutoRoundConfig
```

**Comment by wenhuach21** [comment]
Sorry for the confusion. The AutoRoundConfig  was introduced after version 0.3.0. We'll update the documentation to clarify this. In the meantime, you can install the latest version from the source 
~~~ bash
 git clone https://github.com/intel/auto-round.git && cd auto-round && pip install -vvv --no-build-isolation -e ..
~~~

For version 0.3.0, we recommend using:
~~~python
from auto_round.auto_quantizer import AutoHfQuantizer
~~~
In this version, the device is automatically chosen with GPU and HPU taking priority over CPU. To use the CPU on a CUDA machine, you'll need to modify the model's configuration file.

If you're working with CUDA, you'll need to install from the source to compile the code, as we couldn't include the cuda kernel in the package for various reason

**Comment by wenhuach21** [comment]
updated readme, also the introduction of format you might interested.
Additionally, we plan to release a new version next month, which will address this issue.

**Comment by CrispStrobe** [comment]
many thanks, perfect - and wow, that was swift!

**Comment by sahibpreetsingh12** [comment]
Is the issue still there because I am still getting the issue.

**Comment by wenhuach21** [comment]
Apologies for the delay in the release. In the meantime, please use the following import statement for version v0.3
~~~python
from auto_round.auto_quantizer import AutoHfQuantizer
~~~

**Comment by wenhuach21** [comment]
In quantization, the model operates in floating-point format and undergoes fake quantization to simulate the quantization behavior. After the tuning process is complete, this fake model is converted into a true int4 model that adheres to your specified format. So for real inference, we need to import that code for auto-round format or install auto_gptq for gptq format.

Please refer to the ` Model Inference` in README for more details.

**Comment by sahibpreetsingh12** [comment]
Sure
I installed optimum and auto-gptq 
but still getting
ImportError: Loading a GPTQ quantized model requires optimum (`pip install optimum`) and auto-gptq library (`pip install auto-gptq`)

**Comment by wenhuach21** [comment]
> Sure I installed optimum and auto-gptq but still getting ImportError: Loading a GPTQ quantized model requires optimum (`pip install optimum`) and auto-gptq library (`pip install auto-gptq`) I am on a Kaggle kernel so can't refresh

Which format are you using, auto_round or auto_gptq?

For the GPTQ format, installing Optimum and Auto-GPTQ should suffice. If Transformers still throws an exception, please check your environment; you might have multiple environments in use.

For the auto_round format, please follow our readme

**Comment by sahibpreetsingh12** [comment]
The format is 'auto_gptq'
i installed optimum and auto-gptq and auto-round==0.3.0
and for now i am quantising 'facebook/opt-125m' and my kaggle kernel is crashing 
it's 12GB of P-100 GPU
and this is what i am getting 
<img width="980" alt="Screenshot 2024-09-29 at 9 44 33 PM" src="https://github.com/user-attachments/assets/24a16ff9-f0c8-499f-9cab-80e6f4251751">

**Comment by wenhuach21** [comment]
remove the second line and try again, if it's ok,  it seems a bug in our code.
It it's not ok, try to inference this model ybelkada/opt-125m-gptq-4bit in your env.

**Comment by sahibpreetsingh12** [comment]
I did removed the second line and for my model 'facebook/opt-125m' and i got
<img width="866" alt="Screenshot 2024-09-29 at 9 58 43 PM" src="https://github.com/user-attachments/assets/d56abb9b-5852-4be4-be0c-6cfb66411c71">
but when i did inference with 'ybelkada/opt-125m-gptq-4bit' yes i got results

**Comment by wenhuach21** [comment]
Then you export to AutoRound format model rather than AutoGPTQ format. For AutoRound format, you'll need to install it from source with CUDA support. I recommend switching to the Auto-GPTQ format, but please note that it may have accuracy issues with asymmetric quantization.
~~~python
autoround.save_quantized(output_dir, format='auto_gptq', inplace=True) 
~~~

**Comment by sahibpreetsingh12** [comment]
Yes I already saved in 'auto-gptq' format

**Comment by sahibpreetsingh12** [comment]
But still no inference

**Comment by wenhuach21** [comment]
> I did removed the second line and for my model 'facebook/opt-125m' and i got <img alt="Screenshot 2024-09-29 at 9 58 43 PM" width="866" src="https://private-user-images.githubusercontent.com/28131231/371920265-d56abb9b-5852-4be4-be0c-6cfb66411c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NjMxNTMsIm5iZiI6MTcyNzY2Mjg1MywicGF0aCI6Ii8yODEzMTIzMS8zNzE5MjAyNjUtZDU2YWJiOWItNTg1Mi00YmU0LWJlMGMtNmNmYjY2NDExYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDAyMjA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZTdiNDlhZjAwMTJlMTA3Yjc3MDZmODM1MGJiMmQzYmVhOTU5Zjk3YzI0ZjdiMjM1ZGE5YzI4Njg4ODAwODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9WEqk89l7ZQdVkIMk7cRFUhr9rJ4pmmntqVbekI8xS4"> but when i did inference with 'ybelkada/opt-125m-gptq-4bit' yes i got results

still this issue?

**Comment by wenhuach21** [comment]
That's interesting! I assume you're still exporting to the AutoRound format. I ran the following code on version 0.3.0, and it worked fine. Please check the config.json in the quantized model directory; the quant_method should be set to 'gptq' if the format is auto_gptq.

~~~python
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "facebook/opt-125m"
model = AutoModelForCausalLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

from auto_round import AutoRound

bits, group_size, sym = 4, 128, False
autoround = AutoRound(model, tokenizer, bits=bits, group_size=group_size, sym=sym)


autoround.quantize()
output_dir = "./tmp_autoround"
## format= 'auto_round'(default in version>0.3.0), 'auto_gptq'(default in version<=0.3.0), 'auto_awq'
autoround.save_quantized(output_dir, format='auto_gptq', inplace=True) 
```

~~~

**Comment by sahibpreetsingh12** [comment]
yes this is working 
can you send me the version that worked for inference of this same model.
Because what is their in documentation is not working for me

**Comment by wenhuach21** [comment]
this is the AutoGPTQ format,  I just use the same code in readme
~~~ python
from transformers import AutoModelForCausalLM, AutoTokenizer

quantized_model_path = "./tmp_autoround"
model = AutoModelForCausalLM.from_pretrained(quantized_model_path,
                                             device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(quantized_model_path)
text = "There is a girl who likes adventure,"
inputs = tokenizer(text, return_tensors="pt").to(model.device)
print(tokenizer.decode(model.generate(**inputs, max_new_tokens=50)[0]))
~~~

**Comment by sahibpreetsingh12** [comment]
i dont know how its happening
but i did quantized it in 'auto_gptq' format and saved the file in zip and when i upload it on another kaggle notebook 'config.json' spits out 'auto-round' format

**Comment by sahibpreetsingh12** [comment]
and finally it worked

**Comment by sahibpreetsingh12** [comment]
One another question @wenhuach21 when i am doing the quantisation for phi-2
using GPTQ format i am getting this 
<img width="1005" alt="Screenshot 2024-09-29 at 11 52 46 PM" src="https://github.com/user-attachments/assets/a89b283b-48e6-44e3-a091-e94bc95449b5">
and this is my code
`from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "microsoft/phi-2"
model = AutoModelForCausalLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

from auto_round import AutoRound

bits, group_size, sym = 4, 128, False

# fast and low memory, 2-3X speedup, slight accuracy drop at W4G128
autoround = AutoRound(model, tokenizer, nsamples=128, iters=200, seqlen=512, batch_size=4, bits=bits, group_size=group_size, sym=sym)

autoround.quantize()
output_dir = "./sahib_autorounds_phi2"
## format= 'auto_round'(default in version>0.3.0), 'auto_gptq'(default in version<=0.3.0), 'auto_awq'
autoround.save_quantized(output_dir, format='auto_gptq', inplace=True) `

**Comment by wenhuach21** [comment]
I could not reproduce this issue. May I know your transformer version?
BTW, for phi-2, you'd better set sym=True due to the kernel issue of GPTQ.

**Comment by wenhuach21** [comment]
beside, could you attach the output of Line 1171

**Comment by wenhuach21** [comment]
> One another question @wenhuach21 when i am doing the quantisation for phi-2 using GPTQ format i am getting this <img alt="Screenshot 2024-09-29 at 11 52 46 PM" width="1005" src="https://private-user-images.githubusercontent.com/28131231/371941393-a89b283b-48e6-44e3-a091-e94bc95449b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTE5MDEsIm5iZiI6MTcyODM1MTYwMSwicGF0aCI6Ii8yODEzMTIzMS8zNzE5NDEzOTMtYTg5YjI4M2ItNDhlNi00NGUzLWEwOTEtZTk0YmM5NTQ0OWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAxNDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Mjc4ZWJkODgxZjk3MzZmNTkyNDNmMzM5NDAxNTFjNWI0MWQ4OTA1MmZkNTRmMTQ0Njc5YWU0OTlmZmNkNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gRVyR8jpL9xtQgdqC41_nOj0Vn0N1IjzAtP_N5Cz7Ys"> and this is my code
> 
> ```
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
> model_name = "microsoft/phi-2"
> model = AutoModelForCausalLM.from_pretrained(model_name)
> tokenizer = AutoTokenizer.from_pretrained(model_name)
> 
> from auto_round import AutoRound
> 
> bits, group_size, sym = 4, 128, False
> 
> 
> autoround = AutoRound(model, tokenizer, nsamples=128, iters=200, seqlen=512, batch_size=4, bits=bits, group_size=group_size, sym=sym)
> 
> autoround.quantize()
> output_dir = "./sahib_autorounds_phi2"
> ## format= 'auto_round'(default in version>0.3.0), 'auto_gptq'(default in version<=0.3.0), 'auto_awq'
> autoround.save_quantized(output_dir, format='auto_gptq', inplace=True) `
> ```

I can reproduce the issue. https://github.com/intel/auto-round/issues/271
