### ISSUE TITLE
How to make "try_cache_inter_data_gpucpu" be faster?

### ISSUE THREAD

**Issue by mxjmtxrm** [intel/auto-round#391]
Hi, 
I notice that in function "try_cache_inter_data_gpucpu", the model will be moved to GPU or CPU (if GPU memory is not enough). When I tired to quantize a large scale, the model moved to CPU and the process of caching intermediate input is very slow. And it doesn't make sense to use "device_map=auto" when load hf models.
Is it possible to optimise this function？

**Comment by wenhuach21** [comment]
Set `--device` to 0,1 to utilize multiple GPUs for calibration.
 However, this behavior on your side might seem a bit unusual. When quantizing a typical LLM, we only need to cache the inputs for the first block. This means only the embedding layer requires inference, which is quite fast, even for 70B models on our hardware.
For VL models or when enabling `quant_lm_head`, a warning should be issued to guide users on utilizing multiple GPUs. You can refer to the relevant implementation here: [autoround.py, Line 638](https://github.com/intel/auto-round/blob/main/auto_round/autoround.py#L638).

**Comment by wenhuach21** [comment]
may I know which model you are quantizing, we could take a look.

**Comment by mxjmtxrm** [comment]
Sorry I used an old version. I tried to quantize llama 70B and it works with the latest version. Thanks.
