### ISSUE TITLE
GPU memery use

### ISSUE THREAD

**Issue by Rain19981998** [intel/auto-round#41]
How much GPU memory and CPU size are required when I quantize the Chatglm3-6B model，I used A100-40G，but get an error ”killed“。

**Comment by wenhuach21** [comment]
please enable low_gpu_mem_usage, we could quantized 70B model on 80GB single card with this setting. If not working, please following the readme in example to set --train_bs 1 --gradient_accumulate_steps 8 like this

**Comment by Rain19981998** [comment]
I used the following code for quantization, but it seems to be running on the CPU：
```
model_name = "/root/xxx"
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=dtype, trust_remote_code=True,device_map = "cuda")
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
bits, group_size, sym = 4, 128, False
autoround = AutoRound(model,tokenizer,datasets=examples, bits=bits, group_size=group_size, sym=sym,device="cuda")
autoround.quantize()
output_dir = "/root/xxx/''
autoround.save_quantized(output_dir)
```

**Comment by wenhuach21** [comment]
Hi
I've just run the following code, which is capable of running on GPU. May I know how you determine the code is running on the CPU. And typically if you run it for the first time, the default dataset preprocessing may take 10-20 minutes for large models.   You could check the gpu consumption after autoround dumped informaiton like this 
"2024-03-19 03:19:41 INFO autoround.py L965: quantizing 1/12, model.decoder.layers.0"


import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from auto_round import AutoRound

model_name = "facebook/opt-125m"

model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype="auto", trust_remote_code=True, device_map="cuda")
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
bits, group_size, sym = 4, 128, False
autoround = AutoRound(model, tokenizer, bits=bits, group_size=group_size, sym=sym, device="cuda")
autoround.quantize()

**Comment by Rain19981998** [comment]
Thank you for your help. I have solved this problem, it seems to be a server issue. I replaced the machine and it was resolved.

**Comment by wenhuach21** [comment]
Okay, please feel free to reach out if you encounter any other issues
