### ISSUE TITLE
8-bit quantization support

### ISSUE THREAD

**Issue by ssuncheol** [intel/auto-round#83]
I was wondering if it supports 8-bit quantization. The example code is as below. 

`python main.py \
  --model_name "" \
  --bits 8 \
  --group_size 128 \
  --train_bs 8 \
  --gradient_accumulate_steps 8 \
  --deployment_device 'gpu' \
  --output_dir "./save_ckpt" `

**Comment by wenhuach21** [comment]
Hi,
As an algorithm, Autoround could supports 2-8 bits for quantization, even other bits if we change the code a little.  However, we leverage the kernels from other amazing repositories like AutoGPTQ and ITREX for real deployment which may have some limitation for the quantization configures which we have not thought tested, just for example, triton backend in AutoGptq does not support 3 bits.

However, fortunately, I  just tested facebook/opt-125m with your command, and it performed well and the saved model could run on GPU.

One soft reminder is we use the default config "--train_bs 8  \ --gradient_accumulate_steps 1 ",  and the config  "--train_bs 1  \ --gradient_accumulate_steps 8 " for save memory. We haven't tried "--train_bs 8  \ --gradient_accumulate_steps 8 " before

**Comment by ssuncheol** [comment]
Thanks! i will try.
