### ISSUE TITLE
Quantization/layer speed is very slow

### ISSUE THREAD

**Issue by Qubitium** [intel/auto-round#88]
Current testing PR #87  and running into very slow quants for a Tinyllama 1.1B test model. 

I am geting ~96s per layer in quantization on 4090 gpu with n_blocks = 1 and ~75s per layer with n_blocks = 2. 

Is this the norm? I am new to autoround so don't have a baseline metric to go by. 

Is gpu quant faster or slower than cpu quant? Are there optimizations to make it faster other than using a smaller model for testing? Thanks!

Env:
Ubuntu 22.04
Torch 2.2.2
Cpu: AMD ZEN3

```
env CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=5 python3 main.py \
--model_name /local/TinyLlama-1.1B-intermediate-step-1341k-3T \
--device 0 \
--group_size 128 \
--bits 4 \
--iters 1000 \
--use_quant_input \
--quant_lm_head \
--n_blocks 4 \
--deployment_device 'gpu' \
--disable_low_gpu_mem_usage \
--output_dir "./tmp_autoround"
```

**Comment by wenhuach21** [comment]
By default, the --iters is set to 200, which offers a satisfactory performance compared to other methods. However, for enhanced accuracy and practical deployment, we recommend increasing the iterations to 1000. During testing phases, you may opt for a minimal iteration count of 2.

**Comment by Qubitium** [comment]
> By default, the --iters is set to 200, which offers a satisfactory acc&speed compared to other methods. However, for enhanced accuracy and practical deployment, we recommend increasing the iterations to 1000. During testing phases, you may opt for a minimal iteration count of 2.

That did the trick. Thanks. By lowering iter and increasing n_blocks to as high as the gpu can handle, I was able to quant super fast.
